name: Coverage

on:
  pull_request:
    branches:
    - develop

jobs:
  test-coverage:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.11.2.1446'

    - name: Setup Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: 21

    - name: Install SUSHI
      run: npm install -g fsh-sushi

    - name: Check out Git repository
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

    - name: Cache Local Maven Repo
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-temurin-17-maven-test-coverage-${{ hashFiles('**/deps.edn') }}

    - name: Build
      working-directory: job-ig
      run: make build

    - name: Test Coverage
      run: make test-coverage

    - name: Codecov Upload
      uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4
      with:
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        file: modules/**/target/coverage/codecov.json
        fail_ci_if_error: true
